FROM postgres:latest

# # install system dependencies
# RUN apt-get update && apt-get install -y netcat

# COPY ./entrypoint.sh /

# # Make the entrypoint script executable
# RUN chmod +x /entrypoint.sh

# ENTRYPOINT ["/entrypoint.sh"]

