services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  redis_data:




