# Generated by Django 5.1.3 on 2025-06-11 17:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                ("business_id", models.AutoField(primary_key=True, serialize=False)),
                ("business_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ScrapeEvent",
            fields=[
                ("scrape_id", models.AutoField(primary_key=True, serialize=False)),
                ("scrape_date", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SubcategoryReview",
            fields=[
                ("subcategory_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "subcategory_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerReview",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "review_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("review", models.TextField(blank=True, db_index=True, null=True)),
                ("overall_rating", models.PositiveSmallIntegerField()),
                (
                    "scrape_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="starbuck.scrapeevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.CharField(blank=True, max_length=50, unique=True)),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="starbuck.business",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scrapeevent",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="starbuck.store"
            ),
        ),
        migrations.CreateModel(
            name="CustomerSubcategoryReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="starbuck.customerreview",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="starbuck.subcategoryreview",
                    ),
                ),
            ],
            options={
                "unique_together": {("review", "subcategory")},
            },
        ),
    ]
