# Generated by Django 5.1.3 on 2025-06-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("starbuck", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store",
            old_name="zip_code",
            new_name="zip",
        ),
    ]
